-- Add missing comments for ai_agents, agent_prompts, audit_logs, saas_apps
-- Generated by Trae AI
-- Date: 2026-01-28

-- =============================================
-- Table: ai_agents (AI Agent 配置表)
-- =============================================
COMMENT ON COLUMN ai_agents.id IS 'Agent 唯一标识 (UUID)';
COMMENT ON COLUMN ai_agents.avatar IS 'Agent 头像 (Emoji 或 URL)';
COMMENT ON COLUMN ai_agents.description IS 'Agent 功能描述';
COMMENT ON COLUMN ai_agents.is_active IS '是否启用';
COMMENT ON COLUMN ai_agents.created_by IS '创建者 ID';
COMMENT ON COLUMN ai_agents.created_at IS '创建时间';
COMMENT ON COLUMN ai_agents.updated_at IS '更新时间';

-- =============================================
-- Table: agent_prompts (Agent 常用提示词库)
-- =============================================
COMMENT ON COLUMN agent_prompts.id IS '提示词唯一标识 (UUID)';
COMMENT ON COLUMN agent_prompts.agent_id IS '所属 Agent ID';
COMMENT ON COLUMN agent_prompts.label IS '提示词标签/标题 (如 "优化需求")';
COMMENT ON COLUMN agent_prompts.content IS '提示词详细内容';
COMMENT ON COLUMN agent_prompts.usage_count IS '使用次数统计';
COMMENT ON COLUMN agent_prompts.created_at IS '创建时间';
COMMENT ON COLUMN agent_prompts.updated_at IS '更新时间';

-- =============================================
-- Table: audit_logs (审计日志表 - 补充字段)
-- =============================================
-- Note: audit_logs might have different schemas in different environments.
-- Adding comments for columns found in backend/sql/audit_logs.sql

-- Ensure core columns also have comments if they were missing in some versions
COMMENT ON COLUMN audit_logs.id IS '日志唯一主键';
COMMENT ON COLUMN audit_logs.created_at IS '日志记录时间';

-- =============================================
-- Table: saas_apps (SaaS 应用表 - 补充字段)
-- =============================================
COMMENT ON COLUMN saas_apps.allowed_origins IS '允许的跨域来源 (CORS)，用于安全配置';
